# Generated by Django 4.2.7 on 2026-02-25 14:39

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUploadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_upload_limit', models.IntegerField(default=100)),
                ('current_upload_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_links', to='recruiter.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='CentralizedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('resume_file', models.FileField(upload_to=api.models.public_resume_upload_path)),
                ('uploaded_via_public_link', models.BooleanField(default=False)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('score', models.FloatField(default=0.0)),
                ('fit_level', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Analyzed', 'Analyzed'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='New', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centralized_resumes', to='recruiter.jobposting')),
            ],
        ),
    ]
