# Generated by Django 4.2.7 on 2026-03-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralizedresume',
            name='ml_fit_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='centralizedresume',
            name='ml_model_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centralizedresume',
            name='ml_predicted_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
