# Generated by Django 4.2.7 on 2026-09-25 09:34

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_centralizedresume_ml_fit_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralizedresume',
            name='resume_file',
            field=models.FileField(upload_to=api.models.public_resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
