# Generated by Django 4.2.7 on 2026-02-25 11:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('required_skills', models.JSONField(default=list, help_text='List of required skill strings')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('avg_salary_min', models.IntegerField(default=0, help_text='Minimum avg salary in USD')),
                ('avg_salary_max', models.IntegerField(default=0, help_text='Maximum avg salary in USD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CandidateAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('full_text', models.TextField(blank=True)),
                ('candidate_name', models.CharField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('extracted_skills', models.JSONField(default=list)),
                ('experience_years', models.FloatField(default=0)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('resume_category', models.CharField(choices=[('technical', 'Technical'), ('management', 'Management'), ('fresher', 'Fresher'), ('other', 'Other')], default='other', max_length=50)),
                ('overall_score', models.FloatField(default=0)),
                ('skill_score', models.FloatField(default=0)),
                ('experience_score', models.FloatField(default=0)),
                ('keyword_score', models.FloatField(default=0)),
                ('education_score', models.FloatField(default=0)),
                ('completeness_score', models.FloatField(default=0)),
                ('job_match_percentage', models.FloatField(default=0)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('career_paths', models.JSONField(default=list)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('selected_job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate.jobrole')),
            ],
            options={
                'verbose_name_plural': 'Candidate Analyses',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
