# Generated by Django 4.2.7 on 2026-03-03 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, help_text='Short professional summary')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('highest_education', models.CharField(blank=True, choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD / Doctorate'), ('other', 'Other')], max_length=50)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('field_of_study', models.CharField(blank=True, help_text='e.g. Computer Science', max_length=200)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('current_job_title', models.CharField(blank=True, max_length=200)),
                ('current_company', models.CharField(blank=True, max_length=200)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('preferred_role', models.CharField(blank=True, help_text='e.g. ML Engineer, Data Scientist', max_length=200)),
                ('expected_salary', models.CharField(blank=True, help_text='e.g. $80k-$100k', max_length=50)),
                ('availability', models.CharField(blank=True, choices=[('immediate', 'Immediately'), ('2_weeks', '2 Weeks Notice'), ('1_month', '1 Month Notice'), ('3_months', '3 Months Notice'), ('not_looking', 'Not Actively Looking')], max_length=50)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
