# Generated by Django 4.2.7 on 2026-03-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_candidateprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/candidates/'),
        ),
    ]
