# Generated by Django 4.2.7 on 2026-09-25 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_remove_candidateprofile_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateanalysis',
            name='resume_file',
            field=models.FileField(upload_to='resumes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
