# Generated by Django 4.2.7 on 2026-03-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_remove_recruiterprofile_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrainingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('training_dataset_size', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('precision', models.FloatField(default=0)),
                ('recall', models.FloatField(default=0)),
                ('f1_score', models.FloatField(default=0)),
                ('roc_auc', models.FloatField(default=0)),
                ('cv_accuracy', models.FloatField(default=0, help_text='Cross-validation accuracy')),
                ('confusion_matrix', models.JSONField(default=list)),
                ('training_time', models.FloatField(default=0, help_text='Training time in seconds')),
                ('is_best', models.BooleanField(default=False)),
                ('model_file_path', models.CharField(blank=True, max_length=500)),
                ('training_session', models.CharField(blank=True, help_text='Groups models trained together', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
